version: '3.8'

services:
  useres:
    image: users:01  # Tu imagen personalizada
    container_name: users
    ports:
      - "3000:3000"
    networks:
      - appnet
  items:
    image: items:01  # Tu imagen personalizada
    container_name: items
    ports:
      - "3002:3002"
    networks:
      - appnet
  categories:
    image: cmontellano/categories:01  # Tu imagen personalizada
    container_name: categories
    ports:
      - "3005:3005"
    networks:
      - appnet


networks:
  appnet:
    driver: bridge
